package enums;

public enum Header {
    INITCRYPTO,
    VERIFYCRYPTO,
    VALIDCRYPTO,
    REGISTER,
    SIGNIN,
    SIGNOUT,
    REQUESTUSERS,
    REQUESTGROUPS,
    ADDUSER,
    JOINGROUP,
    MESSAGESENT,
    MESSAGERECEIVED,
    ACCEPTFRIEND,
    DECLINEFRIEND,
    CHATINITIALIZED,
    GROUPINITIALIZED
}
